# Generated by Django 4.1.2 on 2022-10-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='notes',
            field=models.TextField(),
        ),
    ]
