# Generated by Django 4.1 on 2022-12-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='budget.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget.label'),
        ),
    ]
