# Generated by Django 4.1 on 2022-12-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
